move to web
soaptherope/AndersetHotelProject pull request #6
Opened 2024-11-12 16:33 UTC by soaptherope

2024-11-12 16:35 UTC, soaptherope commented
i really hope we dont need tests =)

2024-11-12 17:35 UTC, Alexmansar requested changes
@soaptherope Hi)) in general good job)
about tests - we still can use mock for it ))

2024-11-12 17:35 UTC, Alexmansar commented on src/main/java/org/andersen/Main.java
>      public static void main(String[] args) {
do we still need it?

2024-11-12 17:51 UTC, soaptherope commented on src/main/java/org/andersen/Main.java
>      public static void main(String[] args) {
why? i removed everything from main because i launch not main method but tomcat

2024-11-12 21:20 UTC, soaptherope commented
added tests for the 2 controllers

2024-11-12 22:59 UTC, soaptherope commented on src/main/java/org/andersen/Main.java
>      public static void main(String[] args) {
i create an apartment in web applications not in main

2024-11-13 10:52 UTC, Alexmansar commented on src/main/java/org/andersen/Main.java
>      public static void main(String[] args) {
I mean, maybe we can remove whole class?

2024-11-13 10:54 UTC, Alexmansar requested changes
@soaptherope 
Hi)) good job)) Small comments))

2024-11-13 10:54 UTC, Alexmansar commented on src/main/java/org/andersen/controller/ApartmentController.java
> +        public void init() {
what again happened here?

2024-11-13 10:54 UTC, Alexmansar commented on src/test/java/controller/ApartmentControllerTest.java
> +        lenient().when(request.getServletContext().getRequestDispatcher("/WEB-INF/jsp/apartments.jsp")).thenReturn(dispatcher);
please, don't use lenient()
just use when where we  need it)

2024-11-13 10:54 UTC, Alexmansar commented on src/test/java/controller/ReservationControllerTest.java
> +        lenient().when(request.getServletContext()).thenReturn(servletContext);
same

2024-11-13 13:18 UTC, Alexmansar approved these changes
@soaptherope Hi) please, merge it))

2024-11-13 13:35 UTC, merged