add hibernate
soaptherope/AndersetHotelProject pull request #9
Opened 2024-11-19 23:32 UTC by soaptherope

2024-11-19 23:33 UTC, soaptherope commented
will rewrite tests and ci tomorrow)

2024-11-20 17:33 UTC, soaptherope commented
okay, all good =)

2024-11-20 18:14 UTC, Alexmansar requested changes
@soaptherope 
iN GENERAL GOOD JOB) jUST FEW COMMENTS

2024-11-20 18:14 UTC, Alexmansar commented on src/main/java/org/andersen/model/Apartment.java
>  @Data
https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/
please, read the article. don't use Data with Enitties))

2024-11-20 18:14 UTC, Alexmansar commented on src/main/java/org/andersen/service/ApartmentService.java
>      List<Apartment> sortByNameOfClient(int pageNumber, int pageSize);
maybe we can use it in the separate interface, like ApartmentSortService
and here you just new fields?

or, create 1 basic interface, but generic))
same for repo

2024-11-20 18:47 UTC, soaptherope commented on src/main/java/org/andersen/model/Apartment.java
>  @Data
got it, we only need to compare primary keys and see that they are not null

2024-11-22 19:34 UTC, merged